describe('Testing Spotify Clone', () => {
  it('render login page', () => {
    cy.visit('http://localhost:3000')
    cy.wait(2000)
    // not click in the button beacuse Cypress doesnt allow double url
  })
  it('click to login with spotify and testing dashboard', async () => {
    cy.visit('https://accounts.spotify.com/authorize?client_id=741c3f6f609d4219bf2974cc40b43326&response_type=code&redirect_uri=http://localhost:3000&scope=streaming%20user-read-email%20user-read-private%20user-library-read%20user-library-modify%20user-read-playback-state%20user-modify-playback-state')
    cy.wait(2000)
    cy.get('[data-testid="login-username"]').type('31x5ot6oa2rhjihuj4loma7t2kvq')
    cy.get('[data-testid="login-password"]').type('Sebastian0818')
    cy.wait(2000)
    cy.get('[data-testid="login-remember"]').click({force: true})
    cy.wait(1000)
    cy.get('[data-testid="login-button"]').dblclick({force: true})
    cy.wait(3000)
    cy.get('[data-testid="toggleDarkMode"]').click()
    cy.wait(1000)
    cy.get('[placeholder="Artist, Song, Lyrics and More"]').type('Peaku{enter}')
    cy.wait(5000)
    cy.get('[data-testid="tracks-resulst"]').first().click({force: true})
    cy.wait(3000)
    cy.get('[data-testid="buttonDown"]').click({force: true})
    cy.wait(3000)
    cy.get('[data-testid="tracks-resulst"]').last().click({force: true})
    cy.wait(3000)
    cy.get('[placeholder="Artist, Song, Lyrics and More"]').type('this song not exist - melend_ez{enter}')
  })
})